CREATE TABLE IF NOT EXISTS tournaments( id INTEGER PRIMARY KEY AUTOINCREMENT, tournament_id INTEGER, approved INTEGER );
CREATE TABLE IF NOT EXISTS matches( id INTEGER PRIMARY KEY AUTOINCREMENT, tournament_id INTEGER, match_id INTEGER, post_id TEXT, finished INTEGER, date_played TEXT );
CREATE TABLE IF NOT EXISTS replies( id INTEGER PRIMARY KEY AUTOINCREMENT, comment_id TEXT );
